### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by otreblan** [cs2901-2021-1/lab10-sec01-reward-dining-clean-isiiiftmo#1]
- [ ] SessionManager
- [ ] Consumer (Miembro)
    - [ ] Cena
    - [ ] Reseña
    - [ ] Registro tarjeta
    - [ ] Lista de correo
- [ ] Producer (Rapid)
    - [ ] Cena
    - [ ] Reseña
    - [ ] Registro tarjeta
    - [ ] Lista de correo
- [ ] JSON
    - [ ] Cena
    - [ ] Reseña
    - [ ] Registro tarjeta
    - [ ] Lista de correo
